
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "leftPLUSMINUSleftTIMESDIVIDEDIVIDE IDENTIFIER MINUS NUMBER PLUS TIMESexp : exp PLUS exp\n           | exp MINUS exp\n           | exp TIMES exp\n           | exp DIVIDE expexp : '(' exp ')'exp : IDENTIFIERexp : NUMBER"
    
_lr_action_items = {'(':([0,2,5,6,7,8,],[2,2,2,2,2,2,]),'IDENTIFIER':([0,2,5,6,7,8,],[3,3,3,3,3,3,]),'NUMBER':([0,2,5,6,7,8,],[4,4,4,4,4,4,]),'$end':([1,3,4,10,11,12,13,14,],[0,-6,-7,-1,-2,-3,-4,-5,]),'PLUS':([1,3,4,9,10,11,12,13,14,],[5,-6,-7,5,-1,-2,-3,-4,-5,]),'MINUS':([1,3,4,9,10,11,12,13,14,],[6,-6,-7,6,-1,-2,-3,-4,-5,]),'TIMES':([1,3,4,9,10,11,12,13,14,],[7,-6,-7,7,7,7,-3,-4,-5,]),'DIVIDE':([1,3,4,9,10,11,12,13,14,],[8,-6,-7,8,8,8,-3,-4,-5,]),')':([3,4,9,10,11,12,13,14,],[-6,-7,14,-1,-2,-3,-4,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'exp':([0,2,5,6,7,8,],[1,9,10,11,12,13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> exp PLUS exp','exp',3,'p_exp_binop','parser.py',15),
  ('exp -> exp MINUS exp','exp',3,'p_exp_binop','parser.py',16),
  ('exp -> exp TIMES exp','exp',3,'p_exp_binop','parser.py',17),
  ('exp -> exp DIVIDE exp','exp',3,'p_exp_binop','parser.py',18),
  ('exp -> ( exp )','exp',3,'p_exp_group','parser.py',23),
  ('exp -> IDENTIFIER','exp',1,'p_exp_var','parser.py',31),
  ('exp -> NUMBER','exp',1,'p_exp_numeral','parser.py',36),
]
